# =======================================
# NOTE TO FUTURE SELF: DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU'RE DOING.
# ALSO, THE CHOICES IN THIS FILE ARE NOT BEING USED YET, BUT THEY WILL BE IN THE FUTURE, SO DO NOT DELETE THEM.
# =======================================

challenge_images = [
   {
        "file": "a_matter_of_time.webp",
        "answer": "a matter of time",
        "hints": [
            "It's an idiom.",
            "It means something is inevitable.",
            "It has to do with time."
        ],
        "choices": [
            "bewitched",
            "a matter of time",
            "street by street"
        ]
    },
    {
        "file": "assassination_classroom.webp",
        "answer": "assassination classroom",
        "hints": [
            "It's a title of a work.",
            "It's an anime/manga.",
            "It involves a class trying to kill their teacher."
        ],
        "choices": [
            "assassination classroom",
            "death note",
            "fullmetal alchemist"
        ]
    },
    {
        "file": "attack_on_titan.jpg",
        "answer": "attack on titan",
        "hints": [
            "It's a title of a work.",
            "It's an anime/manga.",
            "It involves giant humanoid creatures attacking humanity."
        ],
        "choices": [
            "attack on titan",
            "your lie in april",
            "cowboy bebop"
        ]
    },
    {
        "file": "black_clover.webp",
        "answer": "black clover",
        "hints": [
            "It's a title of a work.",
            "It's an anime/manga.",
            "It involves a boy born without magic in a world where magic is everything."
        ],
        "choices": [
            "black clover",
            "my hero academia",
            "one piece"
        ]
    },
    {
        "file": "blue_jellyfish.webp",
        "answer": "blue jellyfish",
        "hints": [
            "It's a type of animal.",
            "It's a marine creature.",
            "It's known for its bioluminescence."
        ],
        "choices": [
            "blue jellyfish",
            "giant squid",
            "sea turtle"
        ]
    },
    {
        "file": "both_sides.webp",
        "answer": "both sides",
        "hints": [
            "It's a phrase.",
            "It means considering two perspectives.",
            "It's an album made by two members of the same group."
        ],
        "choices": [
            "both sides",
            "two sides",
            "different sides"
        ]
    },
    {
        "file": "brandy.jpg",
        "answer": "brandy",
        "hints": [
            "She's a musician.",
            "She's known for her distinctive voice.",
            "She had a hit song called 'Always On My Mind.'"
        ],
        "choices": [
            "brandy",
            "monica",
            "aaliyah"
        ]
    },
    {
        "file": "bts.jpg",
        "answer": "bts",
        "hints": [
            "They're a music group.",
            "They're from South Korea.",
            "They have a huge global fanbase called ARMY."
        ],
        "choices": [
            "bts",
            "blackpink",
            "twice"
        ]
    },
    {
        "file": "charlotte.webp",
        "answer": "charlotte",
        "hints": [
            "It's a title of a work.",
            "It's an anime.",
            "It involves teenagers with supernatural abilities."
        ],
        "choices": [
            "charlotte",
            "clannad",
            "angel beats"
        ]
    },
    {
        "file": "chroma_drift.jpg",
        "answer": "chroma drift",
        "hints": [
            "It's a song.",
            "It was made by a Kpop group.",
            "It's by Plave."
        ],
        "choices": [
            "chroma drift",
            "dynamite",
            "idol"
        ]
    },
    {
        "file": "cinema_paradise.webp",
        "answer": "cinema paradise",
        "hints": [
            "It's a title of an album.",
            "It was made by a Kpop group.",
            "It's by Zerobaseone."
        ],
        "choices": [
            "cinema paradise",
            "Youth In The Shade",
            "Map Of Soul: 7"
        ]
    },
    {
        "file": "code_geass.jpg",
        "answer": "code geass",
        "hints": [
            "It's a title of a work.",
            "It's an anime.",
            "It involves a rebellion against an empire and a mysterious power called Geass."
        ],
        "choices": [
            "code geass",
            "gachiakuta",
            "steins gate"
        ]
    },
    {
        "file": "cowboy_bebop.webp",
        "answer": "cowboy bebop",
        "hints": [
            "It's an anime.",
            "It's a space western.",
            "It follows a group of bounty hunters traveling in their spaceship called the Bebop."
        ],
        "choices": [
            "cowboy bebop",
            "beserk",
            "fruits basket"
        ]
    },
    {
        "file": "darwin.webp",
        "answer": "darwin",
        "hints": [
            "He's a fictional character.",
            "He's a fish with legs.",
            "He's from the animated show 'The Amazing World of Gumball.'"
        ],
        "choices": [
            "darwin",
            "gumball",
            "peter"
        ]
    },
    {
        "file": "ditto.jpg",
        "answer": "ditto",
        "hints": [
            "It's an song.",
            "It's by a Kpop group.",
            "It's by NewJeans."
        ],
        "choices": [
            "ditto",
            "hype boy",
            "attention"
        ]
    },
    {
        "file": "do_not_touch.webp",
        "answer": "do not touch",
        "hints": [
            "It's a song.",
            "It's by a Kpop group.",
            "It's by Misamo."
        ],
        "choices": [
            "do not touch",
            "yummy",
            "peaches"
        ]
    },
    {
        "file": "doughnut.png",
        "answer": "doughnut",
        "hints": [
            "It's a song.",
            "It's a Japanese winter song.",
            "It's by Twice."
        ],
        "choices": [
            "doughnut",
            "cookie",
            "cake"
        ]
    },
    {
        "file": "dream_()_scape.webp",
        "answer": "dream()scape",
        "hints": [
            "It's an album.",
            "It has the song, 'Carat Cake.'",
            "It's by Nct Dream."
        ],
        "choices": [
            "dream()scape",
            "map of soul-7",
            "thriller"
        ]
    },
    {
        "file": "empathy.png",
        "answer": "empathy",
        "hints": [
            "It's an album.",
            "It has the song 'Yesterday.'",
            "It's by Nct U."
        ],
        "choices": [
            "empathy",
            "youth in the shade",
            "you had me at hello"
        ]
    },
    {
        "file": "favorite.png",
        "answer": "favorite",
        "hints": [
            "It's an album.",
            "It has the songs 'Favorite' and 'Love On The Floor.'",
            "It's by Nct 127."
        ],
        "choices": [
            "favorite",
            "limitless",
            "0 mile"
        ]
    },
    {
        "file": "fire_force.webp",
        "answer": "fire force",
        "hints": [
            "It's an anime.",
            "One of the openings is called 'Inferno.'",
            "It's about pyrokinetics fighting supernatural creatures after people are turned into monsters."
        ],
        "choices": [
            "fire force",
            "black clover",
            "sword art online"
        ]
    },
    {
        "file": "horimiya.webp",
        "answer": "horimiya",
        "hints": [
            "It's an show.",
            "It's a romance anime.",
            "It's about a shy guy and a popular girl falling for each other."
        ],
        "choices": [
            "horimiya",
            "gachiakuta",
            "ouran high school host club"
        ]
    },
    {
        "file": "i_am_a_ghoul.webp",
        "answer": "i am a ghoul",
        "hints": [
            "The scene is from Tokyo Ghoul.",
            "The person is Ken Kaneki.",
            "The answer is what he said after his hair turned white from being tortured for so long by Jason."
        ],
        "choices": [
            "plus ultra",
            "i am a ghoul",
            "domain expansion"
        ]
    },
    {
        "file": "in_bloom_starting_screen.webp",
        "answer": "in bloom starting screen",
        "hints": [
            "The scene is from a mv.",
            "It's from a Kpop song.",
            "The scene starts with a buttefly as the camera moves to a bunch of people in a garden."
        ],
        "choices": [
            "in bloom starting screen",
            "take my hand starting screen",
            "feel the pop starting screen"
        ]
    },
    {
        "file": "in_bloom.webp",
        "answer": "in bloom",
        "hints": [
            "It's the name of a song.",
            "It's a Kpop song.",
            "It's the name of Zerobasone's debut song."
        ],
        "choices": [
            "in bloom",
            "into the new world",
            "no more dream"
        ]
    },
    {
        "file": "into_the_new_world.webp",
        "answer": "into the new world",
        "hints": [
            "It's a song.",
            "It was made by a girl group.",
            "It is Girls Generation's debut song."
        ],
        "choices": [
            "into the new world",
            "hot times",
            "you, you"
        ]
    },
    {
        "file": "istj.jpg",
        "answer": "istj",
        "hints": [
            "It's a song!",
            "It was made by a boy group!",
            "It was made by Nct Dream!"
        ],
        "choices": [
            "hmph",
            "focus",
            "istj"
        ]
    },
    {
        "file": "k_c_undercover.jpg",
        "answer": "k.c. undercover",
        "hints": [
            "It's a show.",
            "Zendaya is in the show.",
            "It's about a family being undercover spies."
        ],
        "choices": [
            "the amazing world of gumball",
            "spongebob",
            "k.c. undercover"
        ]
    },
    {
        "file": "kaguya_sama_love_is_war.webp",
        "answer": "kaguya-sama love is war",
        "hints": [
            "It's an anime.",
            "It's a romance anime.",
            "It's a girl and a guy falling in love with each other after falling out of a talking stage."
        ],
        "choices": [
            "fruits basket",
            "kaguya-sama love is war",
            "charlotte"
        ]
    },
    {
        "file": "ken_kaneki.webp",
        "answer": "ken kaneki",
        "hints": [
            "It's an anime character.",
            "He has white hair.",
            "He almost died in episode one as he lost half of his humanity."
        ],
        "choices": [
            "ken kaneki",
            "riize",
            "miyuki"
        ]
    },
    {
        "file": "lelouch_and_suzaku.jpg",
        "answer": "lelouch and suzaku",
        "hints": [
            "It's a duo of characters.",
            "They're from the same anime.",
            "Both of them are from Code Geass."
        ],
        "choices": [
            "lelouch and suzaku",
            "gumball and darwin",
            "luffy and zoro"
        ]
    },
    {
        "file": "loud_house.webp",
        "answer": "loud house",
        "hints": [
            "It's a show.",
            "It's about a boy with 10 sisters.",
            "It's a Nickelodeon show."
        ],
        "choices": [
            "loud house",
            "spongebob",
            "the amazing world of gumball"
        ]
    },
    {
        "file": "milo_murphy's_law.jpg",
        "answer": "milo murphy's law",
        "hints": [
            "It's a show.",
            "It's about a boy who has Murphy's Law, which means that anything that can go wrong will go wrong.",
            "It's a Disney show."
        ],
        "choices": [
            "milo murphy's law",
            "gravity falls",
            "phineas and ferb"
        ]
    },
    {
        "file": "mint_condition.webp",
        "answer": "mint condition",
        "hints": [
            "It's a boy band.",
            "They're from the 90s.",
            "They had a hit song called 'Breakin' My Heart (Pretty Brown Eyes).'"
        ],
        "choices": [
            "mint condition",
            "new edition",
            "jodeci"
        ]
    },
    {
        "file": "mordecai_and_rigby.jpg",
        "answer": "mordecai and rigby",
        "hints": [
            "They're a duo of characters.",
            "They're from the same show.",
            "They're best friends who work at a park together."
        ],
        "choices": [
            "mordecai and rigby",
            "gumball and darwin",
            "luffy and zoro"
        ]
    },
    {
        "file": "on_my_youth.jpg",
        "answer": "on my youth",
        "hints": [
            "It's a song.",
            "The people who made the song are under SM, a K-pop company!",
            "The song is related NCT!"
        ],
        "choices": [
            "on my youth",
            "deep ocean",
            "moonwalk"
        ]
    },
    {
        "file": "perfect_velvet.webp",
        "answer": "perfect velvet",
        "hints": [
            "It's an album!",
            "It has the song 'Peek-a-Boo.'",
            "It was made by Red Velvet."
        ],
        "choices": [
            "red velvet",
            "kiikii",
            "babymonster"
        ]
    },
    {
        "file": "perfume.jpeg",
        "answer": "perfume",
        "hints": [
            "It's a song.",
            "It was made by NCT Dojaejung.",
            "It was a debut song!"
        ],
        "choices": [
            "can we go back",
            "perfume",
            "yummy"
        ]
    },
    {
        "file": "phineas_and_ferb.jpg",
        "answer": "phineas and ferb",
        "hints": [
            "It's a show.",
            "It's about two stepbrothers who have fun during their summer vacation.",
            "It's a Disney show."
        ],
        "choices": [
            "phineas and ferb",
            "gravity falls",
            "milo murphy's law"
        ]
    },
    {
        "file": "plave.jpg",
        "answer": "plave",
        "hints": [
            "They're a solo artist.",
            "They're from South Korea.",
            "They have a song called 'Chroma Drift.'"
        ],
        "choices": [
            "plave",
            "seventeen",
            "twice"
        ]
    },
    {
        "file": "poppop.webp",
        "answer": "poppop",
        "hints": [
            "It's a song.",
            "It was made by a Kpop group.",
            "It's by Nct Wish."
        ],
        "choices": [
            "poppop",
            "yummy",
            "peaches"
        ]
    },
    {
        "file": "russian_roulette.webp",
        "answer": "russian roulette",
        "hints": [
            "It's a song.",
            "It was made by a girl group.",
            "It's by Red Velvet."
        ],
        "choices": [
            "russian roulette",
            "red flavor",
            "bad boy"
        ]
    },
    {
        "file": "sad_song.webp",
        "answer": "sad song",
        "hints": [
            "It's a song.",
            "It was made by a Kpop group.",
            "It's by P1Harmony."
        ],
        "choices": [
            "sad song",
            "glow",
            "dynamite"
        ]
    },
    {
        "file": "spongebob.jpg",
        "answer": "spongebob",
        "hints": [
            "He's a cartoon character.",
            "He lives in a pineapple under the sea.",
            "He's a yellow sponge."
        ],
        "choices": [
            "spongebob",
            "the amazing world of gumball",
            "phineas and ferb"
        ]
    },
    {
        "file": "summer_camp_island.jpg",
        "answer": "summer camp island",
        "hints": [
            "It's a show.",
            "It's about two best friends who go to a summer camp on an island.",
            "It's a Cartoon Network show."
        ],
        "choices": [
            "summer camp island",
            "the amazing world of gumball",
            "phineas and ferb"
        ]
    },
    {
        "file": "supernatural.webp",
        "answer": "supernatural",
        "hints": [
            "It's a song.",
            "It was made by a Kpop group.",
            "It's by New Jeans."
        ],
        "choices": [
            "supernatural",
            "russian roulette",
            "perfume"
        ]
    },
    {
        "file": "the_ghost_and_molly_mcgee.webp",
        "answer": "the ghost and molly mcgee",
        "hints": [
            "It's a show.",
            "It's about a ghost and a girl named Molly.",
            "It's a Disney show."
        ],
        "choices": [
            "the ghost and molly mcgee",
            "phineas and ferb",
            "milo murphy's law"
        ]
    },
    {
        "file": "the_perfect_red_velvet.webp",
        "answer": "the perfect red velvet",
        "hints": [
            "It's an album.",
            "It has the song 'Perfect Velvet.'",
            "It's by Red Velvet."
        ],
        "choices": [
            "the perfect red velvet",
            "russian roulette",
            "perfume"
        ]
    },
    {
        "file": "the_velvet.png",
        "answer": "the velvet",
        "hints": [
            "It's an album.",
            "It has the song 'One Of These Nights.'",
            "It's by Red Velvet."
        ],
        "choices": [
            "the velvet",
            "russian roulette",
            "perfume"
        ]
    },
    {
        "file": "tokyo_ghoul.webp",
        "answer": "tokyo ghoul",
        "hints": [
            "It's an anime.",
            "It involves ghouls who eat humans.",
            "The main character is Ken Kaneki."
        ],
        "choices": [
            "tokyo ghoul",
            "death note",
            "attack on titan"
        ]
    },
    {
        "file": "txt.jpg",
        "answer": "txt",
        "hints": [
            "They're a music group.",
            "They're from South Korea.",
            "They have a fandom called MOA."
        ],
        "choices": [
            "txt",
            "bts",
            "seventeen"
        ]
    },
    {
        "file": "we_bare_bears.jpg",
        "answer": "we bare bears",
        "hints": [
            "It's a show.",
            "It's about three bears who are brothers.",
            "It's a Cartoon Network show."
        ],
        "choices": [
            "we bare bears",
            "the amazing world of gumball",
            "phineas and ferb"
        ]
    },
    {
        "file": "your_lie_in_april.webp",
        "answer": "your lie in april",
        "hints": [
            "It's an anime.",
            "It's about a boy and a girl who fall in love.",
            "The main character is Kousei."
        ],
        "choices": [
            "your lie in april",
            "kaguya-sama: love is war",
            "spice and wolf"
        ]
    }
]
